# Generated by Django 4.1.2 on 2022-12-01 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moment_text', models.TextField(help_text='Text body for a Moment')),
                ('moment_created', models.DateTimeField(help_text='Moment created at')),
                ('moment_edited', models.DateTimeField(blank=True, help_text='Moment last edited at', null=True)),
                ('moment_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['moment_created'],
            },
        ),
    ]
