# Generated by Django 4.1.2 on 2022-11-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moment_text', models.TextField(help_text='Text body for a Moment')),
                ('moment_created', models.DateTimeField(help_text='Moment created at')),
                ('moment_edited', models.DateTimeField(help_text='Moment last edited at')),
            ],
            options={
                'ordering': ['moment_created'],
            },
        ),
    ]
