# Generated by Django 4.1.2 on 2022-11-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymoments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='moment_edited',
            field=models.DateTimeField(help_text='Moment last edited at', null=True),
        ),
    ]
