# Generated by Django 4.1.2 on 2022-12-06 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymoments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moment',
            options={'ordering': ['-moment_created']},
        ),
    ]
