# Generated by Django 4.1.2 on 2022-12-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymoments', '0002_alter_moment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='moment_created',
            field=models.DateTimeField(auto_now_add=True, help_text='Moment created at'),
        ),
    ]
