# Generated by Django 4.1.2 on 2022-12-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymoments', '0003_alter_moment_moment_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='moment_edited',
            field=models.DateTimeField(auto_now=True, help_text='Moment last edited at', null=True),
        ),
    ]
