# Generated by Django 4.1.2 on 2022-12-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymoments', '0004_alter_moment_moment_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='moment_edited',
            field=models.DateTimeField(blank=True, help_text='Moment last edited at', null=True),
        ),
    ]
